---
---
- name: Install MongoDB on Linux
  hosts: node1
  become: yes

  tasks:
    - name: Add MongoDB repository for Ubuntu/Debian
      apt_repository:
        repo: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse'
        state: present
        filename: 'mongodb-org-6.0'
    
    - name: Install MongoDB packages
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Ensure MongoDB service is started
      service:
        name: mongod
        state: started
        enabled: yes

...