---
- name: Install and Configure MongoDB
  hosts: node1
  become: yes

  tasks:
    - name: Add MongoDB repository
      yum_repository:
        name: mongodb-org-6.0
        description: MongoDB 6.0 Repository
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/6.0/x86_64/
        gpgcheck: 1
        gpgkey: https://www.mongodb.org/static/pgp/server-6.0.asc
        enabled: 1

    - name: Clean yum cache
      command: yum clean all
      args:
        warn: false

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present
        enablerepo: mongodb-org-6.0
        disablerepo: '*'

    - name: Start and Enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Verify MongoDB is running
      command: systemctl is-active mongod
      register: mongo_status
      changed_when: false
      failed_when: mongo_status.rc != 0
      check_mode: no

    - name: Show MongoDB status
      debug:
        var: mongo_status.stdout

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted