---
- name: Install and Configure MongoDB
  hosts: node1
  become: yes

  tasks:
    - name: Update package cache
      yum:
        update_cache: yes

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present
      notify: Restart MongoDB

    - name: Start and Enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Verify MongoDB is running
      command: systemctl is-active mongod
      register: mongo_status
      changed_when: false
      failed_when: mongo_status.rc != 0
      check_mode: no

    - name: Show MongoDB status
      debug:
        var: mongo_status.stdout

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted