---
- name: Install MongoDB on Amazon Linux
  hosts: n1
  become: yes

  tasks:
    - name: Add MongoDB repository
      yum_repository:
        name: MongoDB
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/6.0/x86_64/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-6.0.asc

    - name: Install MongoDB packages
      yum:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes
...