---
- name: Install MongoDB
  hosts: node1
  become: yes
  tasks:

    - name: Add MongoDB repository
      copy:
        dest: /var/www/html
        content: |
          [mongodb-org-6.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/6.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-6.0.asc

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes
...